services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-fastfood
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: .
      dockerfile: Adapters/Primary/FastFood.Migrator/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Adapters/Primary/FastFood.Api/Dockerfile
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "5000:80"
volumes:
  mysql_data: